services:
  AEV-PDF:
    # GitHub Container Registry (Recommended)
    # simple mode - ghcr.io/alam00000/AEV-PDF-simple:latest
    # default mode - ghcr.io/alam00000/AEV-PDF:latest
    # Docker Hub (Alternative)
    # simple mode - AEV-PDFteam/AEV-PDF-simple:latest
    # default mode - AEV-PDFteam/AEV-PDF:latest
    image: ghcr.io/alam00000/AEV-PDF-simple:latest
    container_name: AEV-PDF
    restart: unless-stopped
    ports:
      - '8080:8080'
    # For IPv4-only environments
    #environment:
    #  - DISABLE_IPV6=true
